import { combineReducers } from "redux";
import {
  AllItemReducer,
  CreateItemReducer,
  CreateCategoryReducer,
  AllModifierCreateReducer,
  CreateGroupModifierReducer,
  AllCategoryReducer,
  AllGroupModifierReducer,
  AllBlogReducer,
  AllModifierReducer,
  UpdateItemReducer,
  CreateBlogReducer,
  UploadImageReducer,
  deleteCategoryReducer,
  deleteItemReducer,
  deleteModifierReducer,
  deleteGroupModifierReducer,
  AllUserReducer,
  loginReducer,
  deleteAccountReducer,
  deleteBlogReducer,
  updateModifierReducer,
  updateCategoryReducer,
  updateGroupModifierReducer,
  updateBlogReducer,
  AllOrderReducer
} from "../Reducers/ProductReducer";
const rootReducer = combineReducers({
  AllOrderReducer,
  updateBlogReducer,
  updateGroupModifierReducer,
  updateModifierReducer,
  updateCategoryReducer,
  deleteBlogReducer,
  deleteAccountReducer,
  loginReducer,
  AllUserReducer,
  deleteGroupModifierReducer,
  deleteModifierReducer,
  deleteItemReducer,
  deleteCategoryReducer,
  UploadImageReducer,
  AllCategoryReducer,
  AllGroupModifierReducer,
  AllModifierReducer,
  AllItemReducer,
  CreateBlogReducer,
  AllModifierCreateReducer,
  CreateItemReducer,
  CreateCategoryReducer,
  CreateGroupModifierReducer,
  AllBlogReducer,
  UpdateItemReducer
});

export default rootReducer;
