// Constants/Product.js

const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
const GET_ALL_BLOG = "GET_ALL_BLOG";
const GET_ALL_ACCOUNT = "GET_ALL_ACCOUNT";
const GET_ALL_ORDER = "GET_ALL_ORDER";
const GET_ALL_GROUP_MODIFIERS = "GET_ALL_GROUP_MODIFIERS";
const GET_ALL_ITEM = "GET_ALL_ITEM";
const GET_ALL_MODIFIERS = "GET_ALL_MODIFIERS";
const GET_ALL_ITEM_REQUEST = "GET_ALL_ITEM_REQUEST";
const GET_ALL_ITEM_FAIL = "GET_ALL_ITEM_FAIL";
const MODIFIER_CREATE_REQUEST = "MODIFIER_CREATE_REQUEST";
const MODIFIER_CREATE_SUCCESS = "MODIFIER_CREATE_SUCCESS";
const MODIFIER_CREATE_FAIL = "MODIFIER_CREATE_FAIL";
const MODIFIER_CREATE_RESET = "MODIFIER_CREATE_RESET";
const CREATE_ITEM_REQUEST = "CREATE_ITEM_REQUEST";
const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS";
const CREATE_ITEM_FAIL = "CREATE_ITEM_FAIL";
const CREATE_ITEM_RESET = "CREATE_ITEM_RESET";
const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
const CREATE_CATEGORY_FAIL = "CREATE_CATEGORY_FAIL";
const CREATE_CATEGORY_RESET = "CREATE_CATEGORY_RESET";
const GROUP_MODIFIER_REQUEST = "GROUP_MODIFIER_REQUEST";
const GROUP_MODIFIER_SUCCESS = "GROUP_MODIFIER_SUCCESS";
const GROUP_MODIFIER_FAIL = "GROUP_MODIFIER_FAIL";
const GROUP_MODIFIER_RESET = "GROUP_MODIFIER_RESET";

const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
const CREATE_USER_FAIL = "CREATE_USER_FAIL";
const CREATE_USER_RESET = "CREATE_USER_RESET";

const CREATE_BLOG_RESET = "CREATE_BLOG_RESET";
const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL";
const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST";

const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST";
const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
const UPDATE_ITEM_FAIL = "UPDATE_ITEM_FAIL";
const UPLOAD_FAIL = "UPLOAD_FAIL";
const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
const UPLOAD_REQUEST = "UPLOAD_REQUEST";

const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
const DELETE_CATEGORY_FAIL = "DELETE_CATEGORY_FAIL";
const DELETE_CATEGORY_RESET = "DELETE_CATEGORY_RESET";
const DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";
const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS";
const DELETE_ITEM_FAIL = "DELETE_ITEM_FAIL";
const DELETE_ITEM_RESET = "DELETE_ITEM_RESET";
const DELETE_MODIFIER_REQUEST = "DELETE_MODIFIER_REQUEST";
const DELETE_MODIFIER_SUCCESS = "DELETE_MODIFIER_SUCCESS";
const DELETE_MODIFIER_FAIL = "DELETE_MODIFIER_FAIL";
const DELETE_MODIFIER_RESET = "DELETE_MODIFIER_RESET";
const DELETE_GROUP_MODIFIER_REQUEST = "DELETE_GROUP_MODIFIER_REQUEST";
const DELETE_GROUP_MODIFIER_SUCCESS = "DELETE_GROUP_MODIFIER_SUCCESS";
const DELETE_GROUP_MODIFIER_FAIL = "DELETE_GROUP_MODIFIER_FAIL";
const DELETE_GROUP_MODIFIER_RESET = "DELETE_GROUP_MODIFIER_RESET";
const DELETE_ACCOUNT_REQUEST = "DELETE_ACCOUNT_REQUEST";
const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
const DELETE_ACCOUNT_FAIL = "DELETE_ACCOUNT_FAIL";
const DELETE_ACCOUNT_RESET = "DELETE_ACCOUNT_RESET";
const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";
const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL";
const DELETE_BLOG_RESET = "DELETE_BLOG_RESET";
const LOGIN_FAIL = "LOGIN_FAIL";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_REQUEST = "LOGIN_REQUEST";

const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';
const UPDATE_CATEGORY_RESET = 'UPDATE_CATEGORY_RESET';
const UPDATE_MODIFIER_REQUEST = 'UPDATE_MODIFIER_REQUEST';
const UPDATE_MODIFIER_SUCCESS = 'UPDATE_MODIFIER_SUCCESS';
const UPDATE_MODIFIER_FAIL = 'UPDATE_MODIFIER_FAIL';
const UPDATE_MODIFIER_RESET = 'UPDATE_MODIFIER_RESET';
const UPDATE_GROUP_MODIFIER_REQUEST = 'UPDATE_GROUP_MODIFIER_REQUEST';
const UPDATE_GROUP_MODIFIER_SUCCESS = 'UPDATE_GROUP_MODIFIER_SUCCESS';
const UPDATE_GROUP_MODIFIER_FAIL = 'UPDATE_GROUP_MODIFIER_FAIL';
const UPDATE_GROUP_MODIFIER_RESET = 'UPDATE_GROUP_MODIFIER_RESET';
const UPDATE_BLOG_REQUEST = 'UPDATE_BLOG_REQUEST';
const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
const UPDATE_BLOG_FAIL = 'UPDATE_BLOG_FAIL';
const UPDATE_BLOG_RESET = 'UPDATE_BLOG_RESET';
const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
const UPDATE_USER_RESET = 'UPDATE_USER_RESET';
const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST';
const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL';
const UPDATE_ORDER_RESET = 'UPDATE_ORDER_RESET';
export {
  UPDATE_ORDER_RESET,
  UPDATE_ORDER_FAIL,
  UPDATE_ORDER_SUCCESS,
  UPDATE_ORDER_REQUEST,
  GET_ALL_ORDER,
  UPDATE_USER_RESET,
  UPDATE_USER_FAIL,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_REQUEST,
  UPDATE_BLOG_RESET,
  UPDATE_BLOG_FAIL,
  UPDATE_BLOG_SUCCESS,
  UPDATE_BLOG_REQUEST,
  UPDATE_GROUP_MODIFIER_RESET,
  UPDATE_GROUP_MODIFIER_FAIL,
  UPDATE_GROUP_MODIFIER_SUCCESS,
  UPDATE_GROUP_MODIFIER_REQUEST,
  UPDATE_MODIFIER_RESET,
  UPDATE_MODIFIER_FAIL,
  UPDATE_MODIFIER_SUCCESS,
  UPDATE_MODIFIER_REQUEST,
  UPDATE_CATEGORY_RESET,
  UPDATE_CATEGORY_FAIL,
  UPDATE_CATEGORY_SUCCESS,
  UPDATE_CATEGORY_REQUEST,
  DELETE_BLOG_RESET,
  DELETE_BLOG_FAIL,
  DELETE_BLOG_SUCCESS,
  DELETE_BLOG_REQUEST,
  DELETE_ACCOUNT_REQUEST,
  DELETE_ACCOUNT_SUCCESS,
  DELETE_ACCOUNT_FAIL,
  DELETE_ACCOUNT_RESET,
  LOGIN_FAIL,
  LOGIN_SUCCESS,
  LOGIN_REQUEST,
  GET_ALL_ACCOUNT,
  DELETE_GROUP_MODIFIER_RESET,
  DELETE_GROUP_MODIFIER_FAIL,
  DELETE_GROUP_MODIFIER_SUCCESS,
  DELETE_GROUP_MODIFIER_REQUEST,
  DELETE_MODIFIER_RESET,
  DELETE_MODIFIER_FAIL,
  DELETE_MODIFIER_SUCCESS,
  DELETE_MODIFIER_REQUEST,
  DELETE_ITEM_FAIL,
  DELETE_ITEM_RESET,
  DELETE_ITEM_SUCCESS,
  DELETE_ITEM_REQUEST,
  DELETE_CATEGORY_REQUEST,
  DELETE_CATEGORY_SUCCESS,
  DELETE_CATEGORY_FAIL,
  DELETE_CATEGORY_RESET,
  UPLOAD_FAIL,
  UPLOAD_SUCCESS,
  UPLOAD_REQUEST,
  CREATE_BLOG_RESET,
  CREATE_BLOG_FAIL,
  CREATE_BLOG_SUCCESS,
  CREATE_BLOG_REQUEST,
  UPDATE_ITEM_REQUEST,
  UPDATE_ITEM_FAIL,
  UPDATE_ITEM_SUCCESS,
  CREATE_USER_REQUEST,
  CREATE_USER_SUCCESS,
  CREATE_USER_FAIL,
  CREATE_USER_RESET,
  GROUP_MODIFIER_FAIL,
  GROUP_MODIFIER_RESET,
  GROUP_MODIFIER_SUCCESS,
  GROUP_MODIFIER_REQUEST,
  CREATE_CATEGORY_REQUEST,
  CREATE_CATEGORY_SUCCESS,
  CREATE_CATEGORY_RESET,
  CREATE_CATEGORY_FAIL,
  GET_ALL_ITEM_FAIL,
  GET_ALL_ITEM_REQUEST,
  GET_ALL_ITEM,
  GET_ALL_CATEGORY,
  GET_ALL_MODIFIERS,
  GET_ALL_GROUP_MODIFIERS,
  GET_ALL_BLOG,
  MODIFIER_CREATE_REQUEST,
  MODIFIER_CREATE_SUCCESS,
  MODIFIER_CREATE_FAIL,
  MODIFIER_CREATE_RESET,
  CREATE_ITEM_REQUEST,
  CREATE_ITEM_SUCCESS,
  CREATE_ITEM_FAIL,
  CREATE_ITEM_RESET,
};
